#
# Project config
#

# Jekyll plugins
plugins:
  - jekyll-sitemap

# Set timezone
timezone: Europe/London

# Compile SASS
sass:
  sass_dir: _sass
  style: compressed

# Set base URL
url: 'https://chrisporter.uk'

# Remove file extentions from URLs
permalink: pretty

# Exclude these files from being added to the site build
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'vendor/*']

# Define content collections
collections:
  statements:

# Site meta fallbacks
title: Chris Porter
metaDescription: The tiny online presence of Chris Porter
metaSocialImage: /assets/img/og.jpg